### ISSUE TITLE
alternate ids not found

### ISSUE THREAD

**Issue by sonia-shah** [edm1/gwas-enrichment#1]
Hi, I'm trying to run gwas-enrichment but get the following error:

Loading reference sum stats...
alternate_ids not found in myfile

I did specify the snp column name using  --snpcol

**Comment by edm1** [comment]
Hi, I think it could be that you need to set the chromosome column using `--chrcol`. This is set to "alternate_ids" by default.

**Comment by sonia-shah** [comment]
Thanks will try that.

Best wishes,
Sonia

**Comment by sonia-shah** [comment]
Hi

It’s reading in my summary stats fine but seems to be falling over when reading the ldscore files. I got these from the ldsc github site and have been using for LD score regression analyses.

gwas_enrich_analysis sonia.shah$ gwas-enrichment.py mdd_sumstats hermes_sumstats --ldscstats ../../Software/ldsc/ldscore/eur_w_ld_chr/*l2.ldscore.gz --snpcol rsid --chrcol chr --mafcol maf --bpcol pos
Run arguments:
 ldscbins: 10
 features: None
 sep:
 testcol: frequentist_add_pvalue
 out: out
 log: False
 teststats: ['hermes_sumstats']
 topthresh: 1e-06
 mafrange: 0.02
 test: lower
 mafcol: maf
 missing: ['.', '', 'NA']
 pcol: frequentist_add_pvalue
 bpcol: pos
 supress: False
 nullsize: 100000
 testposrange: None
 chrcol: chr
 snpcol: rsid
 ldscstats: ['../../Software/ldsc/ldscore/eur_w_ld_chr/1.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/10.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/11.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/12.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/13.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/14.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/15.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/16.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/17.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/18.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/19.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/2.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/20.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/21.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/22.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/3.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/4.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/5.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/6.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/7.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/8.l2.ldscore.gz', '../../Software/ldsc/ldscore/eur_w_ld_chr/9.l2.ldscore.gz']
 posrange: 1000
 ldmap: None
 randseed: False
 maxr2: 0.7
 refstats: mdd_sumstats

Loading reference sum stats...
 done
Loading addtional genomic features...
Loading LD scores...
Traceback (most recent call last):
  File "/Users/sonia.shah/Documents/Software/gwas-enrichment/gwas-enrichment.py", line 780, in <module>
    main()
  File "/Users/sonia.shah/Documents/Software/gwas-enrichment/gwas-enrichment.py", line 80, in main
    refdf = load_merge_ldscores(refdf, args.ldscstats)
  File "/Users/sonia.shah/Documents/Software/gwas-enrichment/gwas-enrichment.py", line 501, in load_merge_ldscores
    chrom, snp, bp, l2 = line.rstrip().split("\t")
ValueError: too many values to unpack


Thanks,
Sonia
